export const MAX_QUESTION_LENGTH = 200
export const MAX_ANSWER_LENGTH = 120
export const MAX_PHOTOS_PER_PAGE = 20
export const MAX_PHOTOS_IN_RESULTS = 80
export const MODAL_ACTION_CLOSE = 'MODAL_ACTION_CLOSE'
export const MODAL_ACTION_CONFIRM = 'MODAL_ACTION_CONFIRM'
export const MODAL_ACTION_RETRY = 'MODAL_ACTION_RETRY'